# Generated by Django 5.0.1 on 2024-02-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('room_capacity', models.PositiveIntegerField()),
                ('projector_available', models.BooleanField(default=False)),
            ],
        ),
    ]
